export const GET_PRODUCTS_START = 'DASHBOARD::GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'DASHBOARD::GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'DASHBOARD::GET_PRODUCTS_FAIL';
