export const GET_PRODUCTS_START = 'PRODUCTS::GET_PRODUCTS_START';
export const GET_PRODUCTS_SUCCESS = 'PRODUCTS::GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'PRODUCTS::GET_PRODUCTS_FAIL';
